services:
  web:
    image: nginx:alpine
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - ${PORT}:80
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
